### ISSUE TITLE
[BUG] Flytectl version command doesn't accept `-c`

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1121]
**Describe the bug**
```
flytectl  -c ~/.flyte/config.yaml version
Warn: No metricsProvider set for the workqueue
Error: unknown shorthand flag: 'c' in -c
```

It seems to default to some known location for the config and not accept a config file like the rest of the commands...

**Expected behavior**
It should accept a config file to know which service endpoint to call to get the version from..

**Comment by evalsocket** [comment]
@pmahindrakar-oss  I created a pr to fix this issue

**Comment by evalsocket** [comment]
@pmahindrakar-oss  i created a pr with fix

**Comment by pmahindrakar-oss** [comment]
Sounds good . Thanks @evalsocket for picking it.
We currently dont support the short -c flag and in general across flytectl because the generated pflags currently dont add those.
Since config is persistent flag added in root.go it can be changed to add a short flag.

```

	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", f.FilePathJoin(f.UserHomeDir(), configFileDir, configFileName),
		"config file (default is $HOME/.flyte/config.yaml)")
```
Juts to clarify -c shouldn't be working on any command .
