### ISSUE TITLE
[BUG] Flyteadmin fails the request if there are no inputs/outputs for a node

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1409]
**Describe the bug**
I've a workflow with a single athena-query node. It doesn't take inputs nor does it produce outputs. The workflow succeeds but when I click on the inputs/outputs tabs for the task execution, I get 500 error.

Admin logs show this:
flyteadmin-5498f9cc6d-q4m7l flyteadmin {"json":{"exec_id":"hkbya2soci","node":"n0","src":"aws_remote_url.go:68"},"level":"debug","msg":"failed to get object size for s3://flyte-demo/metadata/propeller/flytesnacks-development-hkbya2soci/n0/data/0/outputs.pb with NotFound: Not Found\n\tstatus code: 404, request id: EKVFWF51NDCXGS4Y, host id: uPn1W8ySqtgyPnucehxHkJ6Cl7wT3p6mKAtR49KIFMCQpYiXCN7Fj96am/SJutVNOmRS/yRjLOI=","ts":"2021-09-01T14:53:37Z"}

**Expected behavior**
No errors.

***Screenshots***
![image](https://user-images.githubusercontent.com/27159/131694050-b54c1f6b-6435-418d-bf50-3c85ede975bf.png)

**Comment by EngHabu** [comment]
cc @katrogan

**Comment by katrogan** [comment]
This occurs when the signed url is fetched for input/output execution data here: https://github.com/flyteorg/flyteadmin/blob/2d81c1eec24cffb43346b56fc0017fd29db33a38/pkg/data/implementations/aws_remote_url.go#L55

we should skip the call to even get the data when the execution interface indicates that there is no input and/or output or handle not founds gracefully somehow (by omitting the signed url from the response)

note: we've since moved to deprecating signed urls and moved to returning execution input/output data inline with GetExecutionData responses by default when such data does not exceed a configured size threshold

**Comment by pmahindrakar-oss** [comment]
@EngHabu @katrogan This is now handled in the following PR 
https://github.com/flyteorg/flyteadmin/pull/250

**Comment by pmahindrakar-oss** [comment]
@EngHabu @katrogan instead of handling not found gracefully or determining from the execution interface that its doesn't have io (BTW there is no such filed which indicates an execution doesnt have any io. Please correct if i am wrong here)
shouldn't we fix wrong data being sent for node execution event from propeller 
if this url doesn't exist then why even construct it and send it in the event
s3://flyte-demo/metadata/propeller/flytesnacks-development-hkbya2soci/n0/data/0/outputs.pb

Please suggest which of the alternatives would be suitable to use here

**Comment by kumare3** [comment]
Since we migrated away from signed urls, this is now fixes
