### ISSUE TITLE
[Docs]flytekit plugin docs improvements in flytesnacks

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1541]
**Describe the documentation update**
Flytesnacks should have  an updated documentation for how to author flytekit plugins
- [ ] SQL plugins
- [x] flytekit only plugins - task template plugin; New doc
   - https://github.com/flyteorg/flyte/pull/986/files
- [x] flytekit template plugins - Template and task plugins are the same. Custom container (task template/template only plugin), custom behavior (flytekit plugin); New page
   - https://www.youtube.com/watch?v=51hWdfVZHbs&t=33s
- [ ] flytekit shim plugins for backend plugins
   - https://www.youtube.com/watch?v=59w9HYOcJJ8&t=1282s
- [x] Type plugins
   - https://www.youtube.com/watch?v=E_X3I5XF-_o
- [ ] Data persistence plugins
   - https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-data-fsspec

**Comment by EngHabu** [comment]
@samhita-alla is this planned for December? maybe as part of the doc-push?

**Comment by samhita-alla** [comment]
> @samhita-alla is this planned for December? maybe as part of the doc-push?

Oh yeah. That sounds good.

**Comment by samhita-alla** [comment]
This issue is partly covered in https://github.com/flyteorg/flyte/issues/834. 

@cosmicBboy, if taking up the above-mentioned issue, which ones would you likely be working on?

**Comment by cosmicBboy** [comment]
Hey @samhita-alla I think some of the problems articulated in #834 have been addressed in this section:
https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/index.html

I think the bullet points above
>  SQL plugins
 flytekit only plugins
 flytekit template plugins
 flytekit shim plugins for backend plugins
 Type plugins
 Data persistence plugins

Can be new pages under the "Extending Flyte" page in flytesnacks.

@kumare3 can you clarify the difference between "flytekit only plugins" and "flytekit template plugins?" Just because I think:
- [this page](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/run_custom_types.html#sphx-glr-auto-core-extend-flyte-run-custom-types-py) already takes care of "Type plugins"
- [this page](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/custom_task_plugin.html#sphx-glr-auto-core-extend-flyte-custom-task-plugin-py) takes care of "flytekit only plugins"

FYI there are these pages in the flytekit API reference:
- https://docs.flyte.org/projects/flytekit/en/latest/extend.html
- https://docs.flyte.org/projects/flytekit/en/latest/tasks.extend.html
- https://docs.flyte.org/projects/flytekit/en/latest/types.extend.html
- https://docs.flyte.org/projects/flytekit/en/latest/data.extend.html

But I think those should basically be a function/class API reference while the new pages under flytesnacks are for user education (and should link to appropriate functions/class in the API reference via intersphinx)

I'm going to close #834. Let me know if you need any help with any

**Comment by cosmicBboy** [comment]
fixes https://github.com/flyteorg/flytesnacks/pull/744

**Comment by cosmicBboy** [comment]
Closing this issue, breaking up the remaining tasks into:
- https://github.com/flyteorg/flyte/issues/2679
- https://github.com/flyteorg/flyte/issues/2680
- https://github.com/flyteorg/flyte/issues/2681

**Comment by cosmicBboy** [comment]
Will close this issue when https://github.com/flyteorg/flytesnacks/pull/744 is merged

**Comment by samhita-alla** [comment]
merged https://github.com/flyteorg/flytesnacks/pull/744
