### ISSUE TITLE
[Housekeeping] Containers should not run as root

### ISSUE THREAD

**Issue by frsann** [flyteorg/flyte#1606]
### Describe the issue

It seems like most Dockerimages related to the project does not define a user/group as which the service is run. This means that the services are run as root. We should fix this, to prevent security issues.

### What if we do not do this?

We run a risk of privilege escalation.  

### Related component(s)

At least flytepropeller, flyteadmin, flyteconsole, and datacatalog. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
Thank you for filing this issue! I 100% agree.. We should update Dockerfiles of all of flyte components to run as user 1001 or something instead.. and a corresponding change in all deployments to let K8s set the right permissions for mounted volumes.

Is this something you might be able to help us do? even if it's just for one component so that people can start copying what you did into others? @frsann

**Comment by frsann** [comment]
@EngHabu I made some PRs that hopefully fixes the issues.
