### ISSUE TITLE
[Feature request] Use type annotations 

### ISSUE THREAD

**Issue by betodealmeida** [flyteorg/flyte#171]
Currently Flyte uses decorators to indicate the types of input and outputs, [for example](https://github.com/lyft/flytesnacks/blob/master/python/single_step/edges.py):

```python
@inputs(image_location=Types.String)
@outputs(parsed_image=Types.Blob)
@python_task
def edge_detection_canny(wf_params, image_location, parsed_image):
    pass
```

It would be nice if it could use [type annotations](https://docs.python.org/3/library/typing.html) instead, so that one could write:

```python
@python_task
def edge_detection_canny(
    wf_params: Any,
    image_location: Types.String,
    parsed_image: Types.Blob,
) -> None:
    pass
```

I haven't looked deeply into the source code, but I believe this should be possible to do by extending the `python_task` decorator to analyze the type annotations in the function signature using the [inspect module](https://docs.python.org/3/library/inspect.html#inspect.signature).

@senthilnathan23 and I are willing to work on a PR for this, if there's interest.

**Edit:** I just realized we still need a way to differentiate inputs from outputs. Is there any reason why the tasks modify the output inplace, instead of returning it?

**Comment by kumare3** [comment]
@betodealmeida this is one of our roadmap items and help wanted :). We have a lot of ideas on how we can do this, but at the moment we are on limited resources. The API that you see today exists because FlyteKit was initially written for flyte2.7 (3 years ago). But with 2.7 EOL I think we should completely move to using typing. It should not be that much work, but still needs dedicated effort.

Differentiating inputs should not be that hard. Would love to collaborate and work on this

**Comment by kumare3** [comment]
Also to add to your request
```
import pandas as pd
import numpy as np

@python_task
def my_function(ctx: flyte.Context, s: str, arr: np.ndarray[str]) -> pd.DataFrame:
   ...
```
Improve accessibility of data (files and dirs instead of blobs and multipart blobs :P)
```
@python_task
def my_function(ctx: flyte.Context, s: flyte.File, d: flyte.Dir): flyte.File

OR just python File
And when you say open(File) we can download
```

**Comment by betodealmeida** [comment]
@kumare3 awesome, I'll work on a spec with @senthilnathan23
