### ISSUE TITLE
Allow securityContext and podSecurityContext to be specified for tasks using the Spark plugin

### ISSUE THREAD

**Issue by akumor** [flyteorg/flyte#1854]
### Describe the bug

A security context defines privilege and access control settings for a Pod or Container according to https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

For Spark tasks, there is currently no way to specify these settings as either part of the task or part of the configuration of the backend flytepropeller plugin.

### Expected behavior

Security context configuration should be accepted for Spark tasks.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@akumor thank you for the issue, do you think this should be settable per task / execution or a global default is good enough?

**Comment by akumor** [comment]
In my specific case, the Kubernetes cluster I run on has [Gatekeeper](https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/) enabled to ensure pods conform to certain security settings.  Having the container/pod security context be a global default is good enough for me.

**Comment by kumare3** [comment]
To recap these values are all settable on the SparkApplication CRD - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L495-L500.
But SparkApplicationCRD does not completely be faithful to a pod spec. It replicates some field.
In the spark plugin, this is also done weirdly, just because as the CRD has evolved the plugin has evolved. 
IMO, the best way to do  this would be to 
 1. Get a default Flyte K8s podspec from the TaskTemplate
 2. Write a translator function, that translates attrs from a regular podspec to the Sparkapplication CRD pod spec
 3. As new features are added this can be simply modified. This will also allow things like Flyte copilot etc to work automatically.

But, this is out of context for this task. For this task, We should add pod-security-context and container security context to the flytek8s.config section, which will be automatically applied to all pods by default. For spark, this will be done as an additional step. 
As a follow up when we migrate the podspec -> spark CRD translation, these steps can be simply dropped.

cc @akhurana001 / @EngHabu
