### ISSUE TITLE
[FlyteCTL Feature] add the ability to pass environment variables to the docker run command

### ISSUE THREAD

**Issue by anmyachev** [flyteorg/flyte#2096]
### Describe the feature/command for FlyteCTL

This can be useful, for example, when running a sandbox under a proxy.

### Provide a possible output or UX example

Something like `flytectl start --env https_proxy=$https_proxy --source .`

Or through some config file.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@anmyachev  Thanks for creating the issue, Can you explain little bit more? Who will use the env variable ?

**Comment by anmyachev** [comment]
@evalsocket Hi! Thanks for response. In order for the sandbox to work in an environment with a proxy, I think it's necessary to pass the proxy envs to the `/flyteorg/bin/flyte-entrypoint.sh` script, whose launch chain looks like this: `flytectl sandbox start` -> [docker cli client run](https://github.com/flyteorg/flytectl/blob/9e1971ad05e8cd0ea3ba593500798af8f82cc5c0/cmd/sandbox/start.go#L88) -> `/flyteorg/bin/flyte-entrypoint.sh`.

I only give an example with proxy variables, but it might be worth looking at it more broadly.

**Comment by evalsocket** [comment]
cc: @pmahindrakar-oss

**Comment by pmahindrakar-oss** [comment]
Hi @anmyachev ,
Thanks for opening the issue. Would  you be able to help contributing to enhance flytectl for this behavior.

The change involves
* Introducing a new flag Env []string `json:"env" pflag:",Optional. Provide  Env variable in key=value format which can be passed to sandbox container."`
You can add it after this flag https://github.com/flyteorg/flytectl/blob/9e1971ad05e8cd0ea3ba593500798af8f82cc5c0/cmd/config/subcommand/sandbox/sandbox_config.go#L52
* Generate the code to call to ammend the command to pass this flag https://github.com/flyteorg/flytectl/blob/9e1971ad05e8cd0ea3ba593500798af8f82cc5c0/cmd/config/subcommand/sandbox/sandbox_config.go#L3
* Instead of static ENV list of strings, provide an ability to append to it 
* For multiple env variables , the UX would look like this --env key1=value1 --env key2=value2 and this is automatically supportted after the code is generated in step2
* Enhance the wrapper StartContainer method  to pass in the passed in env variables and ammend to static list 
https://github.com/flyteorg/flytectl/blob/9e1971ad05e8cd0ea3ba593500798af8f82cc5c0/pkg/docker/docker_util.go#L136
