### ISSUE TITLE
[BUG] Newline not stripped from clientSecretLocation when using Config.auto

### ISSUE THREAD

**Issue by danwinkler** [flyteorg/flyte#2480]
### Describe the bug

`flytekit.configuration.Config.auto` returns a `Config` object where `platform.client_credentials_secret` has a newline on the end (which breaks auth with FlyteRemote) when using a config file with `admin.clientSecretLocation`. 

### Expected behavior

The client secret contained in the file specified at `admin.clientSecretLocation` should have its newline stripped from the end before being put into a `Config` object.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
Hey @danwinkler, just discussed this with Katrina. While it's technically possible to do that, I think this may lead to unexpected behavior because the secret should be opaque to Flytekit/FlyteRemote... it's typically mounted by an external system (in CI... etc.) as a file and should be just used as is. It's conceivable to have a secret with `\n` at the end (it's a valid UTF-8 character after all). 

Please let me know what you think...

**Comment by danwinkler** [comment]
Hey @EngHabu, I was trying to be [unixy](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) and thus had a newline at the end of my secret on my dev machine. 

After searching around a bit, it seems like most projects have the behavior you suggest, which is to not mess with the contents of the file. Unfortunate given how many unix tools introduce newlines, but correct behavior nonetheless. Learned something new today!

Thanks!
