### ISSUE TITLE
[BUG] Collisions on subworkflow launchplan execution IDs

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#2778]
### Describe the bug

When a launchplan is executed as part of a Flyte workflow FlytePropeller is responsible for generating an execution ID. This algorithm must be deterministic so that subsequent workflow processing checks the correct launchplan execution ID to retrieve status. Currently it [uses a 32bit hash](https://github.com/flyteorg/flyteplugins/blob/c4de2d719cb26f62b89d64f27023e84993906647/go/tasks/pluginmachinery/encoding/encoder.go#L21-L26) of the subworkflow node ID. However, this only produces a 8 character (actually 7 and 1 padded) execution ID. With a large number of launchplan executions collisions may occur.

### Expected behavior

Launchplan executions ID should never collide.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
For an immediate fix we will update the hashing algorithm to 64bit (or 128bit?) to increase the length of the hash. This should significantly reduce the probability of a collision. However, in the very small chance a collision would still occur we should implement some additional logic to check for an existing execution before starting the launchplan.

**Comment by EngHabu** [comment]
I've considered a few different options, after a brief chat with Dan, I think we should proceed with the one in the above PR.

Options:
1. Upgrade hashing algorithm to 64bit
   Pros: simple change.
   Cons: No easy way for backward compatibility. If an existing execution is in "flight", subsequent checks for the health/status of the execution will result in building a different execution id and subsequently failing.

1. Add static Version in NodeStatus/WFNodeState
  Similar to EventVersion in Admin, we can have a NodeStatusVersion global field and store that into every node status (or at the CRD level). We can then bump it to indicate the change in hashing algorithm... New executions use the new hashing algorithm and in-flight ones keep using the 32bit one
   Pros: Straightforward to implement
   Cons: Leaves if/elses all around. Potentially making debugging harder.

1. Add HashingAlgorithm to the WFNodeState
   (similar to the option before) For new launch plan executions, it can always use 64bit and store that fact into the WF Node State. When checking for LP Status, if the alg bit is set, we use that, otherwise fallback to the 32bit algorithm.

1. Prefix the 32bit hash with the WF Exec ID
   Cons: Could potentially be longer than Admin allows (it allows 20characters) if the original exec id is already 20 characters, the 32bit one is 8 characters, we can then remove the last 8 characters of the original exec id...

## Detecting collisions
* Admin today detect collisions and returns "Already exists" iff exec name matches an existing one. We can modify that behavior to check for collisions in `parent node exec id` column as well and return a different error if the execID matches but the parent doesn't (e.g. `Belongs to a different Execution`-Error)... Propeller can react differently to this error (possibly by either erroring out early for now)

**Comment by hamersaw** [comment]
@EngHabu my only comment deals with maintaining versions in differing locations moving forward, for example if we chose to add a CRD version we will have (1) individual component version (ie. eventing like you mentioned + current others), (2) our newly defined CRD version which is incremented for any changes moving forward, and (3) the k8s CRD resource version (currently v1alpha1), but I know we discussed moving this if we update the CRD to store strict binary for space savings (what is the relationship between a v1beta1 release and our flyte workflow version?). I don't feel strongly about any of these options - but I think it is important to give some thought on the implications of adding another version. Any choice we can probably do some refactoring to clean versions not conforming to the new "standard".
