### ISSUE TITLE
[Docs] Have a note specifying version shouldn't have a forward slash

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2782]
### Description

Reference Slack thread: https://discuss.flyte.org/t/2400153/i-have-solved-the-problem-not-found-error-i-mentioned-yester

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@pmahindrakar-oss , can we detect if a '/' is used in the version in flytectl instead of relying on a note in the docs? In other words, why is '/' a valid character in the version?

**Comment by pmahindrakar-oss** [comment]
@eapolinario from the conversation I couldn't get the info on which exact command they used for registration .
But we should prevent this from all clients and hence should be a flyteadmin change.there should be a validation for version names to not contains such characters.I agree instead of a Doc this should be a code change
