### ISSUE TITLE
[BUG] version parameter is not being used in `flytectl get task` 

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3301]
### Describe the bug

`flytectl get task` lists all tasks of a given project and domain. One of the parameters of that command is `--version` (or `--latest`), which allows you to list tasks for a specific version. That parameter is not being honored currently. 

### Expected behavior

`flytectl get task --project <project> --domain <domain> --version <version>` should return all tasks for version `<version>`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
Hi @eapolinario , the expected behavior is to pass the task name to get its particular version

eg: 
` flytectl get task -p flytesnacks -d development   core.flyte_basics.task_cache.compare_dataframes --version v0.3.65`

I think you want the version parameter to list all tasks with that version which seems to be an enhancement wherein if you dont pass the task name then the behavior should be different i.e it get all tasks for version v

This can be achieved through this for eg:

```
flytectl get task -p flytesnacks -d development --filter.fieldSelector="task.version=v0.3.65" -o yaml
```

That behavior can be added as an enhancement but this doesn't seem to be a bug because this is as per initial design.

**Comment by eapolinario** [comment]
Thanks for clarifying, @pmahindrakar-oss .
