### ISSUE TITLE
[BUG] Dynamic workflows won't run with `flytekit>=1.3.0`

### ISSUE THREAD

**Issue by bstadlbauer** [flyteorg/flyte#3324]
### Describe the bug

After upgrading to `flytekit>=1.3.0`, the following error message appears when workflows are run: 

```
Workflow[dask-plugin:development:demo.dask_demo.workflows.dynamic_workflow] failed. RuntimeExecutionError: max number of system retry attempts [11/10] exhausted. Last known status message: InvalidArgument: Invalid fields for event message, caused by [rpc error: code = InvalidArgument desc = missing project]
```

Example workflow: 
```python
from flytekit import workflow, task, dynamic


@task
def some_task():
    print("Do something")


@dynamic
def dynamic_task():
    some_task()


@workflow
def dynamic_workflow():
    dynamic_task()
```

The workflow was serialized using `pyflyte -k <package> serialize --image <image> workflows -f <output_dir`.

A bit of investigation lead to possibly https://github.com/flyteorg/flytekit/pull/1378 being the root cause of this.

### Expected behavior

The dynamic workflow should run

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Speaking about the plan for this bug. We're [reverting](https://github.com/flyteorg/flytekit/pull/1460) the offending change and getting a patch release of flytekit out (version 1.3.2).

Members of the core team got together earlier today and the consensus is that we have a bug in the backend, more specifically the compiler, but while we work on a fix, we're mitigating this issue by the plan described ahead. 

We decided against yanking the versions 1.3.0 and 1.3.1 of flytekit because this bug only affects dynamic workflows.

**Comment by eapolinario** [comment]
Just adding a breadcrumb, https://github.com/flyteorg/flyte/issues/3169#issuecomment-1379684751 describes the rationale for the offending change. 

We'll be revisiting this in the next few days.

**Comment by lindseynield** [comment]
@eapolinario do you know when the 1.3.2 patch will get propagated to the [feedstock](https://github.com/conda-forge/flytekit-feedstock)?

**Comment by eapolinario** [comment]
@lindseynield , 1.3.2 change is happening in https://github.com/conda-forge/flytekit-feedstock/pull/38.

**Comment by eapolinario** [comment]
> @eapolinario do you know when the 1.3.2 patch will get propagated to the [feedstock](https://github.com/conda-forge/flytekit-feedstock)?

@lindseynield , flytekit 1.3.2 is in conda: https://anaconda.org/conda-forge/flytekit
