### ISSUE TITLE
[Docs] Where do I find the aks values to deploy to my Azure cluster?

### ISSUE THREAD

**Issue by joaoloboguerra** [flyteorg/flyte#3331]
### Description

Hey everyone.
I would like help configuring Flyte on my AKS cluster, above my ask for us.
I'm new here, and I got a task from my boss to install Flyte on the cluster and release it for my ML team to test on it.

I can't deploy flyte to my cluster because I can't find how to configure it
I located this documentation
`https://docs.flyte.org/en/latest/deployment/deployment/multicluster.html`

and this other one I only find the values of **GCP** and **AWS**
`https://github.com/flyteorg/flyte/tree/master/charts/flyte-binary`

I need help if anyone can support me for Azure (aks) thanks
### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by joaoloboguerra** [comment]
I can deploy in AKS, closed this issue

**Comment by bensonchen-tomtom** [comment]
Hi @joaoloboguerra 
Could you share the values or examples you used for deploying to AKS? I had the flyte-binary deployed to AKS already, but when trying to run `pyflyte run --remote basics/hello_world.py hello_world_wf` it raised SSL error for me. I guessed it could be caused because I didn't have the correct values.yaml setting for Azure. I'm referring to the [eks-starter.yaml](https://github.com/flyteorg/flyte/blob/master/charts/flyte-binary/eks-starter.yaml) for AWS.
