### ISSUE TITLE
[BUG] Swagger UI not accessible from the sandbox

### ISSUE THREAD

**Issue by aswanthkrishna** [flyteorg/flyte#3350]
### Describe the bug

unable to access redoc swagger UI after starting the sandbox at localhost:3081/openapi as mentioned in the [documentation]. (https://docs.flyte.org/en/latest/reference/swagger.html#reference-swagger)

### Expected behavior

Should be able to see the swagger API documentation after navingating to localhost:3081/openapi after launching the sandbox container.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
just wanted to say that the redocly container was indeed dropped from the new sandbox.  the reason is size, and performance.  The new sandbox has all the dependent images built-in, like downloaded and saved, which improves start-up time.  Bundling in yet another thing just seemed unnecessary... the actual swagger doc is still available though. Navigate to http://localhost:30080/api/v1/openapi with the demo cluster running.
