### ISSUE TITLE
[BUG] Flyteconsole >= 1.4.8 front page and other pages broken

### ISSUE THREAD

**Issue by sbrunk** [flyteorg/flyte#3485]
### Describe the bug

The layout of flyteconsole is broken in multiple places. Especially the front page isn't working at all. This happens in the `1.4.1` release, i.e. if you install current helm chart or run `flytectl demo`.

Downgrading to console `1.4.8` helps as a workaround.

Console front page:
![grafik](https://user-images.githubusercontent.com/3939659/225873852-ef2a4e21-97a6-4d7d-b9bc-881515ba1d5a.png)

Workflow page:
![grafik](https://user-images.githubusercontent.com/3939659/225874145-6bd1da2a-ed77-4e51-80b2-7c991c79ebf6.png)

### Expected behavior

Flyteconsole should show projects on the front page and other pages without broken layout.

### Additional context to reproduce

Update flyteconsole to `1.4.8` or higher

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
hey @sbrunk thanks for reporting this! can you provide some instructurions on how to reproduce these errors?

**Comment by jsonporter** [comment]
Yeah unfortunately it was a regression involving MUI but its been fixed in both [flyteConsole v1.5.2](https://github.com/flyteorg/flyteconsole/releases/tag/v1.5.2) as well as the latest [flyte release v1.4.2](https://github.com/flyteorg/flyte/releases/tag/v1.4.2)

Closing this ticket as the issue has been resolved.
