### ISSUE TITLE
[Docs]  Instructions to run propeller locally are not working

### ISSUE THREAD

**Issue by sonjaer** [flyteorg/flyte#3637]
### Description

https://github.com/flyteorg/flytepropeller/tree/master#running-propeller-locally
* The link to the config is dead. 
* It says "cd into this folder", but its not clear which folder
* flytepropeller command is not detected 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
Hey @sonjaer! Sorry, these docs are certainly out of date. We have been planning to update for some time, but in switching over to a monorepo (all Flyte golang components in a single git repo) we have put this off because it will change how development is performed.

Can I ask what your goal is here? I would be happy to talk about the current dev setup and how that will be changed, but don't want to overload on unnecessary information.

**Comment by sonjaer** [comment]
> Hey @sonjaer! Sorry, these docs are certainly out of date. We have been planning to update for some time, but in switching over to a monorepo (all Flyte golang components in a single git repo) we have put this off because it will change how development is performed.
> 
> Can I ask what your goal is here? I would be happy to talk about the current dev setup and how that will be changed, but don't want to overload on unnecessary information.

Hi! Just wanted to let you know it was not working. I wanted to run propeller locally, but I already did. I can close this issue if you are already working on it?

**Comment by hamersaw** [comment]
Yeah, I think lets close this one. As part of the monorepo migration we will update the docs for running locally / contributor guides. Thanks!
