### ISSUE TITLE
[Docs] What are the supported PostgreSQL Major versions?

### ISSUE THREAD

**Issue by RRap0so** [flyteorg/flyte#3741]
### Description

_Sorry if I haven't picked the write type._

We couldn't find in the documentation what are the supported PostgreSQL Major version. 

Since updating postgres is time consuming and requires downtime, we would like to know what Postgresql Major versions Flyte will support going forward to plan our upgrades accordingly.

Thanks!

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@rafaelraposospot , we don't have an officially supported version matrix yet. That said, we have seen successful deployments running versions ranging from 10 all the way to 15. 

Also, since most of the interactions happen through gorm and gorm-migrate (i.e. we don't use any postgres-specific extensions or features), I expect that this is going to extend to upcoming postgres 16. I wouldn't be surprised if we were able to run in older versions of Postgres.
