### ISSUE TITLE
[FlyteCTL Feature] Restrict access to users on specific projects

### ISSUE THREAD

**Issue by k-e-r-n-e-l-p-a-n-i-c** [flyteorg/flyte#3909]
### Describe the feature/command for FlyteCTL

Hello Team,

We are exploring Flyte and it looks fantastic. However, we would like to restrict/allow users to access specific projects. Based on our study about Flyte, we understand that, at the moment such feature isn't available but there was a proposal to use OPA gate keeper to implement it. 

Can you please let us know if there is any other method to have such kind of granular permissions for Flyte users per project? We will be integrating Flyte with IAM (probably Keycloak) tool.

Regards,

### Provide a possible output or UX example

Feature to allow restrict/allow users to specific Flyte projects.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
@k-e-r-n-e-l-p-a-n-i-c the feature you describe sounds more like RBAC which, as you already found out, is not planned to be part of OSS Flyte. The reason is twofold: 1. The lack of a robust and widely-accepted framework/standard for RBAC, like OAuth2.0 is for authorization. 2. As a consequence, an in-tree implementation of RBAC in this scenario would require a higher effort to be maintained and extended to fit the numerous ways to do RBAC. 

That's why currently only the Flyte managed service (Union Cloud) includes an implementation of RBAC.

OPA Gatekeeper is great for K8s-scoped Admission Control but there would be rough edges to cut for a real RBAC experience for Flyte-managed resources.

Flyte ships with SSO, even with an embedded auth server and the ability to leverage your IdP (Keycloak, for example) at different levels. If you need any help setting up auth, we're happy to collaborate.

Thanks!

**Comment by k-e-r-n-e-l-p-a-n-i-c** [comment]
Thanks @davidmirror-ops
