### ISSUE TITLE
[Docs]  ImageSpec docs 404

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#4009]
### Description

Searching from the `docs.flyte.org` and even from external search engines leads to a broken link

https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/image_spec/index.html#id1

<img width="1184" alt="image" src="https://github.com/flyteorg/flyte/assets/82604841/2f274f61-89db-419e-b17d-966910156f55">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
added a redirect on readthedocs to `/auto_examples/customizing_dependencies/image_spec.html` as a short-term fix.

[https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/image_spec/index.html](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/image_spec/index.html#id1) doesn't actually exist anymore since we consolidated the one child page to another section
