### ISSUE TITLE
[BUG] Outputs of a subworkflow in a remote launch plan is handled incorrectly

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#4369]
### Describe the bug

https://github.com/flyteorg/flyte/blob/9fe34dbace17037f860c736ba1b8f709ee6cf773/flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go#L283 may not receive full outputs, depending on how `storage.limits.maxDownloadMBs` is configured in flyteadmin, and it does not fail loudly when the outputs size is larger than `storage.limits.maxDownloadMBs`. What's worse is that flytepropeller happily stores the 0-sized protobuf file to be used as the inputs of the following task.

Currently the error message is impossible to understand by users and also very hard for flyte admins to investigate:
```
failed at Node[wxetj-n1]. BindingResolutionError: Error binding Var [wf].[asi], caused by: failed at Node[wxetj-n0]. OutputsNotFoundError: Outputs not found at [gs://.../wxetj-n0/data/0/outputs.pb]
```

### Expected behavior

flytepropeller should fail loudly to indicate that it could not receive expected outputs.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by honnix** [comment]
BTW it is also very confusing having two config items with overlapping purposes:
* `remoteData.maxSizeInBytes`
* `storage.limits.maxDownloadMBs`

**Comment by honnix** [comment]
I think in general having smaller `storage.limits.maxDownloadMBs` values (in flyteadmin, flytepropeller, and datacatalog) configured than `max-output-size-bytes` does not make sense it would fail at different places.

**Comment by hamersaw** [comment]
@honnix this fix is rather confusing given the plethora of configuration options. Do you know if you are using [signed urls](https://github.com/flyteorg/flyte/blob/yushang%2Foverwrite-cache%2Fiteration/flyteadmin/pkg/runtime/interfaces/application_configuration.go#L431-L431)? It seems the [proto support for this flow is deprecated](https://github.com/flyteorg/flyteidl/blob/6eff9b0be4f41b717b2d89697c7187a5216a0547/protos/flyteidl/admin/execution.proto#L307-L313), but none of the configuration options are labeled as such.

The [overall API design](https://github.com/flyteorg/flyte/blob/14915dcb1cbde884c6b8d514114dc48cf1342fbf/flyteadmin/pkg/manager/impl/util/data.go#L98-L131) suggests that fetching output data within admin is "best effort" and if it is not returned then the client should try. This leads me to believe that rather than attempted to return the error value here (in only the correct scenarios) that we should attempt to retrieve the data if it's missing from [flytepropeller when we retrieve the execution](https://github.com/flyteorg/flyte/blob/d981a96fe86feff4dec9caa0cf5b603e7dcd8648/flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go#L266-L283). Thoughts?

@pvditt please comment as well!

**Comment by honnix** [comment]
@hamersaw The signed urls won't help in cases when flytepropeller needs to fetch outputs from flyteadmin for the following task executions and currently it doesn't use signed url for that if I'm not mistaken. Yes the `outputs` is deprecated, but not [full_outputs](https://github.com/flyteorg/flyteidl/blob/6eff9b0be4f41b717b2d89697c7187a5216a0547/protos/flyteidl/admin/execution.proto#L319) which is what flytepropeller reads from.

Regarding retry, yes, if anything is in the critical path, a proper retry sounds like a great idea. In this case, however, a retry would not make any difference because there was no RPC failure so flytepropeller was not able to tell whether a workflow indeed didn't output anything or it was just flyteadmin refusing to fetch due to max size config.

**Comment by pvditt** [comment]
@hamersaw I believe that initial API design intention for retries was for the console. This [PR](https://github.com/flyteorg/flyteconsole/pull/391/files) removed the usage of UrlBlob on the console. I don't believe there's been an expectation of retries on these calls for a while. I made an [issue](https://github.com/flyteorg/flyte/issues/4632) to clean up UrlBlob.

Good call out on retries from propellor. I'll add that to this [PR](https://github.com/flyteorg/flyte/pull/4602).

**Comment by pvditt** [comment]
@hamersaw actually would it make sense to add retries on the propellor side when we already have system error retries?

**Comment by pvditt** [comment]
@honnix this issue should be closed by: https://github.com/flyteorg/flyte/pull/4602

There's a follow-up [house-cleaning issue](https://github.com/flyteorg/flyte/issues/4723) to have that GetExecutionData admin endpoint to bubble errors that I'll be resolving soon that doesn't block closing this issue.

Please feel free to re-open this issue and tag me if this [change](https://github.com/flyteorg/flyte/pull/4602) does not fix the issue.
