### ISSUE TITLE
[Housekeeping] Use msgspec instead of marshmallow and related dependencies

### ISSUE THREAD

**Issue by thomasjpfan** [flyteorg/flyte#4485]
### Describe the issue

Currently, serializing we are using many libraries to serialize objects in `flytekit`:

- mashumaro
- marshmallow
- marshmallow-jsonschema (Last release in 2021-10)
- marshmallow-enum (Last release in 2019-10)

This can all be replaced by replaced by https://github.com/jcrist/msgspec, which has not dependencies itself. `msgspec` contains all the features needed above. <s>`msgspec` has [run benchmarks](https://jcristharif.com/msgspec/benchmarks.html#benchmark-schema-validation) that show favorable results compared to the popular serialization frameworks.</s> Benchmarks could be outdated.

- Related to https://github.com/flyteorg/flyte/issues/4486, which proposes to remove `dataclasses_json`.
- Related to https://github.com/flyteorg/flyte/issues/4418: reduce dependencies.

### What if we do not do this?

Continue to depend on multiple libraries for serialization.

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Fatal1ty** [comment]
Hi, author of mashumaro here 👋

Just to make it clear, mashumaro supports dataclasses out of the box (and don't force you to use mixins since the recent [3.11](https://github.com/Fatal1ty/mashumaro/releases/tag/v3.11) release) and don't depend on any library except typing-extensions (for compatibility reasons). It has nothing to do with marshmallow, marshmallow-jsonschema or marshmallow-enum in favour of built-in JSON Schema generation functionality and standard Enum types support.

> that show favorable results compared to the popular serialization frameworks.

Their [outdated](https://github.com/jcrist/msgspec/issues/523) comparison uses Struct classes written in C for msgspec, and that's why everyone can see the impressive results. If you stick to dataclasses, msgspec won't give you that performance advantage and will run at about the same speed as the others. I encourage you to write your own benchmark to see the difference before making a decision.

**Comment by Future-Outlier** [comment]
#take

**Comment by thomasjpfan** [comment]
With https://github.com/flyteorg/flytekit/pull/2080, we have users that depend on `mashumaro's` API. In this case, I think we should go the other way and go "all in" on `mashumaro`. Specifically, use `mashumaro` directly and remove the need for  `marshmallow` and friends.

With that in mind, I'll close this issue around migrating to `msgspec`.
