### ISSUE TITLE
[BUG] Non-interruptible node selectors added to all subsequent tasks after using spark plugin

### ISSUE THREAD

**Issue by osevin** [flyteorg/flyte#4609]
### Describe the bug

We've been seeing some mysterious non-interruptible node selector affinities since enabling the flyte spark plugin in one of our deployments.

It seems like each time we launch a task that uses the spark plugin it causes an extra non-interruptible-node-selector-requirement to show up (for any future tasks!).
Interruptible tasks are then stuck pending with for example:
          - key: cloud.google.com/gke-spot
            operator: DoesNotExist
          - key: cloud.google.com/gke-spot
            operator: DoesNotExist
          - key: cloud.google.com/gke-spot
            operator: In
            values:
            - "true"

### Expected behavior

We expect there not to be non-interruptible node selectors automatically added after spark tasks

### Additional context to reproduce

We are using flyte-core 1.6.2
spark operator is version 1.1.27
              
spark-config-default:
    - spark.kubernetes.authenticate.driver.serviceAccountName: "flyte-worker"
    - spark.hadoop.fs.gs.project:
        "{{ .Values.userSettings.googleProjectId }}"
    - spark.hadoop.fs.gs.impl: "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    - spark.hadoop.fs.AbstractFileSystem.gs.impl: "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    - spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version: "2"
    - spark.kubernetes.allocation.batch.size: "50"
    - spark.excludeOnFailure.enabled: "true"
    - spark.excludeOnFailure.timeout: "5m"
    - spark.task.maxfailures: "4"
    

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pvditt** [comment]
@osevin 

Thanks for pointing out this issue. I'm not able to reproduce this issue and am not able to identify the bug while stepping through the code. 

Would you be able to reproduce this on a demo cluster?

**Comment by osevin** [comment]
Hey Paul, as mentioned in the slack this is fixed in Flyte 1.10.6, thanks for looking into it.

If you want to understand better what was wrong I can work on the demo but going to go ahead and close it if not.

**Comment by pvditt** [comment]
adding for posterity:

Unsure what I did with my local setup previously, but I tried again and was able to reproduce the issue on Flyte 1.6.2.

The issue was [here](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/k8s/spark/spark.go#L104):
`Affinity:         config.GetK8sPluginConfig().DefaultAffinity,` 
Should be 
`Affinity:         config.GetK8sPluginConfig().DefaultAffinity.DeepCopy()`

This would get set in the spark [driverSpec](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/k8s/spark/spark.go#L102) ->  [resource Spec](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/k8s/spark/spark.go#L217) -> [update node selector requirements](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/k8s/spark/spark.go#L243) altering the set DefaultAffinity until propellor restarts.
The issue was handled with this [PR](https://github.com/flyteorg/flyte/pull/4183/files). (edited)
