### ISSUE TITLE
[Docs] Some P0 tests are broken

### ISSUE THREAD

**Issue by iaroslav-ciupin** [flyteorg/flyte#4764]
### Description

P0 priority tests `data_types_and_io.file.normalize_csv_file` and `data_types_and_io.folder.download_and_normalize_csv_files` are broken. Error:
```
Message:

    Failed to get data from https://people.sc.fsu.edu/~jburkardt/data/csv/biostats.csv to /tmp/flyte2vp55qml/local_flytekit/7c6f30c3abdb118b985175720c546321/biostats.csv (recursive=False).

Original exception: https://people.sc.fsu.edu/~jburkardt/data/csv/biostats.csv

User error.
```
GET https://people.sc.fsu.edu/~jburkardt/data/csv/biostats.csv indeed returns 404 Not Found. Probably, examples/tests should not rely on external data sources that are not hosted by Flyte.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by 10sharmashivam** [comment]
Hi,
I would like to work on this issue. Instead of depending on external resources, I propose using hardcoded CSV data directly in our test cases. This approach will ensure that our tests are stable and not affected by the availability of external files.

Implementing this change will enhance the robustness of our testing framework and make it easier to maintain moving forward.

Please let me know your thoughts on this! #take

**Comment by 10sharmashivam** [comment]
Hi,

I've created the necessary CSV files in the `test_data` folder as part of my work on this issue. However, I've encountered an issue where the CSV files are not showing up in `git status`, while other files, like `.py`, are tracked correctly.

I checked the `.gitignore` file in the repository and noticed that it might be excluding CSV files. Since I cannot modify the `.gitignore` myself, I wanted to reach out to see if the exclusion of CSV files was intentional and, if so, what the reasoning behind it might be.

Here are some troubleshooting steps I've taken:
- Checked for any global `.gitignore` configurations.
- Verified file permissions.
- Created a new test CSV file, which still didn't show up.

I'd appreciate any guidance or insights you could provide regarding this. Thank you!

**Comment by davidmirror-ops** [comment]
@eapolinario @cosmicBboy I guess referencing datasets hosted somewhere else helps keep the repo lightweight, but also may affect the example when those datasets are not available anymore in the hardcoded location. What do you think about hosting datasets used in examples in flytesnacks or static-resources?

**Comment by eapolinario** [comment]
Keeping the necessary datasets in the repo (as long as they are not big files) is the sensible choice. Here's a PR to allow csv files in flytesnacks: https://github.com/flyteorg/flytesnacks/pull/1763

**Comment by 10sharmashivam** [comment]
@davidmirror-ops Since PR for allowing .csv file to be added got merged, I also created test_data folder and and added .csv files. Here is the [PR](https://github.com/flyteorg/flytesnacks/pull/1764).
