### ISSUE TITLE
[Housekeeping] Flyteadmin digest comparison should rely on database semantics

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#4780]
### Describe the issue

In order to compare an already registered task (and workflow, and launch plan) when an identical version is registered, we [get](https://github.com/flyteorg/flyte/blob/8f516e839074d0c1013ab58650a1a0fec575d990/flyteadmin/pkg/manager/impl/task_manager.go#L91-L104) the existing task from the db and manually compare its digest. This is prone to race conditions. It would be better to wrap this in a transaction where we attempt to upsert the task only on a matching digest

### What if we do not do this?

Slightly more error prone method for determining already exists task structure

### Related component(s)

flyteadmin

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by popojk** [comment]
#take

**Comment by popojk** [comment]
Hi @katrogan , I want to clarify the issue before going forward. While creating task, flyte admin will check whether the id and taskDigest of new task is identical to existing task in db. Is this issue aiming to wrap [this section of code](https://github.com/flyteorg/flyte/blob/8f516e839074d0c1013ab58650a1a0fec575d990/flyteadmin/pkg/manager/impl/task_manager.go#L91-L100)  in transaction, in order to prevent others precess possibly update the data of existing task while doing the taskDigest check?

**Comment by katrogan** [comment]
yes exactly, we could have two users attempt to register the same task version in the same time frame such that an existing task digest is never found but only one succeeds in writing to the db

**Comment by popojk** [comment]
Hi @katrogan , please let me clarify this issue further. In [this section of code](https://github.com/flyteorg/flyte/blob/8f516e839074d0c1013ab58650a1a0fec575d990/flyteadmin/pkg/manager/impl/task_manager.go#L91-L120), Flyte will check if identical task existed in the DB. If not, Flyte will create new task in DB, otherwise return error.
Let me make an example(please refer to bellow picture for better understanding). If there are 2 identical tasks, Task A and Task B, assigned to Flyte Admin at the same time frame, it is possible that both tasks will not find each other in the DB, and both tasks will be written into the DB.
If the example I made is the issue you are aiming to handle, I am not sure how transaction can solve the problem as it seems like using transaction will still cause duplicate task creation. In my mind this issue can be solve by something like distributed lock.
Please let me know if I have any misunderstanding,  thanks!
![截圖 2024-11-21 下午3 26 39](https://github.com/user-attachments/assets/ffc7a6aa-c2a7-463c-a0de-a953f60ee1d9)

**Comment by katrogan** [comment]
yes exactly! the way we get around duplicates in the two separate transactions is because we want to guard against two tasks with the same identifier (project, domain, name, version) being written to the db with different structures (which would result in different digests)

the database ensures we can never write duplicate entries with identical primary keys (in this case, [TaskKey](https://github.com/flyteorg/flyte/blob/master/flyteadmin/pkg/repositories/models/task.go#L7-L12))

if we move the digest comparison to within a transaction we can ensure we correctly returns already exists (with or without a different task structure)

so the pseudocode could look like
in the transaction:
try:
  create a task with given primary key
except:
  primary key already exists
  get existing entry with identical primary key
    if digest of existing == new entry's digest -> return `NewTaskExistsIdenticalStructureError`
    else -> return `NewTaskExistsDifferentStructureError`

**Comment by popojk** [comment]
Hi @katrogan , thanks for the detailed explanation. I think I understand the purpose of wrapping digest check within a transaction right now. Just want to clarify with you once again. If the transaction checks the primary key on create task first, and check digest if task of the same primary key found in DB, we can make sure that the digest will be checked even though two identical tasks registered in the same timeframe.

![截圖 2024-11-22 下午5 28 50](https://github.com/user-attachments/assets/af8c890e-1074-45ea-b1ac-198f37b96289)

Moreover, I am not sure about what you mentioned about `NewTaskExistsDifferentStructureError`. If the error occurred, the error message will be something like what in bellow picture, where the message states the difference of origin and new task by [this section of code](https://github.com/flyteorg/flyte/blob/master/flyteadmin/pkg/errors/errors.go#L130-L139). Do you mean we should add additional task information in the closure to the error message and return to client side?

<img width="1323" alt="截圖 2024-11-26 上午11 05 24" src="https://github.com/user-attachments/assets/648705dd-0e7d-4179-a479-4c75e0995564">

**Comment by katrogan** [comment]
great, that diagram looks like we're on the same page!

about `NewTaskExistsDifferentStructureError` that was more of an optimization. what we can do if if the postgres transaction fails due to primary key conflict, return AlreadyExists in the postgres error transformer. The calling code in task_manager can then fetch the existing task definition from the db and determine whether to return `NewTaskExistsDifferentStructureError` or `NewTaskExistsIdenticalStructureError` based on how the digests of the two tasks compare

**Comment by popojk** [comment]
Hi @katrogan , I've raised a [PR](https://github.com/flyteorg/flyte/pull/6058) to address this issue. Please feel free to share any additional thoughts or suggestions, thanks!

**Comment by popojk** [comment]
Hi @katrogan , i've raise a [PR](https://github.com/flyteorg/flyte/pull/6058) for this issue for a while. Could you please help me to review it and let me know if if any adjustment required? Thanks!

**Comment by katrogan** [comment]
hi @popojk thank you so much for the ping, I'm so sorry I missed this notification before!
