### ISSUE TITLE
[BUG]  Can't pickle local object 'get_flyte_fs.<locals>._FlyteFS' (FlyteRemote)

### ISSUE THREAD

**Issue by alexbeach-bc** [flyteorg/flyte#5052]
### Describe the bug

I am attempting to write pulumi dynamic provider in python, which serializes objects in the provider. The issue is that FlyteRemote cannot be serialized with pickle. The following code reproduces the issue:

```python
import pickle
from flytekit.remote import FlyteRemote
from flytekit.configuration import Config

remote = FlyteRemote(
     config=Config.auto(),
     default_project="flytesnacks", 
     default_domain="development"
)
pickle.dumps(remote)
```

```bash
AttributeError: Can't pickle local object 'get_flyte_fs.<locals>._FlyteFS'
```

The issue stems the nested class here:
https://github.com/flyteorg/flytekit/blob/d61e79e722875348b1ccd354e1076fcf12600053/flytekit/remote/remote_fs.py#L91

I am using python 3.12.1, flytekit==1.11.0. 

### Expected behavior

flytekit remote objects are serializable with pickle

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@alexbeach-bc just curious, why do you want to pickle the flytekit remote?

**Comment by alexbeach-bc** [comment]
> @alexbeach-bc just curious, why do you want to pickle the flytekit remote?

I am writing a dynamic provider in pulumi to mange deployments of workflows/projects. Pulumi uses pickle to serialize the providers:

```python
```

**Comment by eapolinario** [comment]
@alexbeach-bc , first of all, thanks for working on this change, it seems very interesting and it will increase the utility of Flyte!

Speaking about your problem specifically, I don't have any experience with pulumi providers, so can you help me understand where the remote object is being serialized? I'm asking because relying on a serialized version of a flyteremote object is difficult, as it contains a reference to the underlying client used to talk to the backend and also credentials, etc. So I want to understand why the object itself has to be serialized instead of being re-hydrated when needed.

**Comment by alexbeach-bc** [comment]
@eapolinario I am not sure actually my approach makes sense for a long term solution anymore. There is a difference between pulumi dynamic providers vs providers, and it i am also not super familiar with pulumi internals, its just that we use pulumi for the majority of our infra.  Pulumi providers can be implemented in a multi-language way, where the above dynamic provider would limit use to python only. I am going to close this for now,.
