### ISSUE TITLE
[BUG] Flytepropeller error and crash when "limit-namespace" is set

### ISSUE THREAD

**Issue by timheb** [flyteorg/flyte#5087]
### Describe the bug

Flytepropeller error and crash of the pod (version 1.11.0, same for version 1.10.6/1.10.7)

```
I0321 12:57:51.491581       1 leaderelection.go:260] successfully acquired lease peach2-flyte/propeller-leader
{"json":{},"level":"panic","msg":"failed to load plugin - container: [PluginInitializationFailed] wrong type. Actual: *cache.multiNamespaceInformer","ts":"2024-03-21T12:57:51Z"}
panic: (*logrus.Entry) 0xc000703880

goroutine 366 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000703810, 0x0, {0xc00013fd00, 0x71})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
github.com/sirupsen/logrus.(*Entry).Log(0xc000703810, 0x0, {0xc000f813d0?, 0x4521720?, 0xc000f813d0?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Entry).Panic(0x2f37ff0?, {0xc000f813d0?, 0x23ac240?, 0x1?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342 +0x25
github.com/flyteorg/flyte/flytestdlib/logger.Panic({0x2f37ff0?, 0xc0009fc5f0?}, {0xc000f813d0, 0x1, 0x1})
	/go/src/github.com/flyteorg/flytestdlib/logger/logger.go:144 +0x47
github.com/flyteorg/flyte/flytepropeller/pkg/controller.(*Controller).onStartedLeading.func1()
	/go/src/github.com/flyteorg/flytepropeller/pkg/controller/controller.go:132 +0x99
created by github.com/flyteorg/flyte/flytepropeller/pkg/controller.(*Controller).onStartedLeading in goroutine 395
	/go/src/github.com/flyteorg/flytepropeller/pkg/controller/controller.go:130 +0xc5
```

### Expected behavior

no crash

### Additional context to reproduce

1. Version 1.9.0 not crash
2. Version 1.10.0 not crash
3. Version 1.10.6 crash
4. Version 1.10.7 crash
5. Version 1.11.0 crash

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ByronHsu** [comment]
I also run into this issue. Will help taking a look

**Comment by ByronHsu** [comment]
Root cause analysis
1. [New Cache](https://github.com/flyteorg/flyte/blob/c81133bfc79e8eb2efb729a5f6e3f972195967e4/flytepropeller/pkg/controller/executors/kube.go#L28) creates a cache (by controller-runtime)
2. [Inside Cache](https://github.com/kubernetes-sigs/controller-runtime/blob/21368602d84b669eacfb36ec49b10a665b2d4d49/pkg/cache/cache.go#L316), it creates multinamespace cache if options.DefaultNamespace exists. Otherwise, create an all namespace cache.
3. In the [plugin manager](https://github.com/flyteorg/flyte/blob/c81133bfc79e8eb2efb729a5f6e3f972195967e4/flytepropeller/pkg/controller/nodes/task/k8s/plugin_manager.go#L671), it tried to get a shared informer. However, it enforces the informer type to be cache.SharedIndexInformer (go-client) but the type is cache.multiNamespaceInformer (controller-runtime) if options.DefaultNamespace exists. 
4. Technically, limit-namespace should be a “list” since the task can be created in multiple namespaces

I haven't found a good solution yet. Flyte mixes the usage of `controller-runtime` cache and `client-go` cache, so what returned from `Cache.New` might not be compatible with returned type (`cache.SharedIndexInformer`)

**Comment by austin362667** [comment]
take

**Comment by austin362667** [comment]
#take

**Comment by MortalHappiness** [comment]
#take

**Comment by wild-endeavor** [comment]
It looks like we upgraded from [0.12.1](https://github.com/flyteorg/flyte/blob/fa49d3bfcdc081328e2f1514fd513ec46fdbf734/flytepropeller/go.mod#L38C33-L38C40) of controller-runtime to [0.16.3](https://github.com/flyteorg/flyte/blob/c049865cba017ad826405c7145cd3eccbc553232/flytepropeller/go.mod#L42) when we added support for open telemetry.  That brought in a whole lot of changes one of which was the [change you](https://github.com/kubernetes-sigs/controller-runtime/compare/v0.12.1...v0.16.3#diff-964e351ee2375d359c78d69e514c4edc42577219761c4475f391ed2daf715e51L153) mentioned @ByronHsu.  How did you find this?  Tracing through, I couldn't find my way to that cache.go function.

I don't think the current proposal quite works though.  We have to do this through the informer.  it's way too expensive to go through the client every time (unless the newer client is somehow already caching things?).

@hamersaw - could you take a look at this when you get a chance please?  i haven't worked with controller runtime enough.

Thanks again for the investigation byron.

**Comment by ByronHsu** [comment]
Thanks @wild-endeavor! bullet 1 is in flyte code, but bullet 2 (cache.go) is in controller-runtime code.
