### ISSUE TITLE
[BUG] Container overrides broken in flytekit 1.11.0

### ISSUE THREAD

**Issue by ai-rnatour** [flyteorg/flyte#5297]
### Describe the bug

See this related [issue](https://github.com/flyteorg/flyte/issues/4493).

This was working for us in version 1.10.2 of `flytekit`, however when we upgraded to 1.11.0 we confirmed that this no longer works. In our case, the default base image is used instead of the runtime override applied through `with_overrides`.

### Expected behavior

When using `with_overrides`, I would expect the `container_image` I provide to override our base image.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
As discussed in https://github.com/flyteorg/flyte/issues/4543#issuecomment-2089279490, this ended up being a breaking change that should have been feature more prominently in the 1.11.0 release notes.

I'm going to close this issue since we cleared the confusion. Let me know if you need to discuss this again.
