### ISSUE TITLE
[Feature] Access control on who can run/view workflows

### ISSUE THREAD

**Issue by senthilnathan23** [flyteorg/flyte#555]
**Motivation: Why do you think this is important?**
We want to have better access control over who can run/view workflows. Currently this is blocker to create any critical pipelines on Flyte.

**Goal: What should the final outcome look like, ideally?**
Flyte UI/CLI: Should allow certain list of users to view/run the workflows. This could be configured through the code.

**Describe alternatives you've considered**
There are no alternatives at this point to overcome this.

**Flyte component**
- [x] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
N/A

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
This is a blocker for us to start using Flyte for our critical data pipelines.

**Comment by kumare3** [comment]
This is something that we want to work on in Milestone Q1, 2021

**Comment by senthilnathan23** [comment]
@kumare3 Thank you for the update. Looking forward to it. Are we planning to use google auth or something different? just curious.

**Comment by kumare3** [comment]
@senthilnathan23 so Flyte already supports OAuth2 based Authentication flow. https://flyte.readthedocs.io/en/latest/administrator/install/authentication.html?highlight=auth. Since this uses OAuth2 you should be able to use Google Auth for the sign in.

This issue aims at implementing Authorization (AuthZ / Role based access control).  I am not 100% sure if we can have RBAC policies in Google. We are definitely thinking on the lines of Open Policy Agent. Would love your thoughts. Please join the slack channel at https://docs.google.com/forms/d/e/1FAIpQLScWPJZncyL-bBCWbuQ9HWuMzA8-r2RJc__CSWJoAYUQADN-BQ/viewform and join the discussin

**Comment by kumare3** [comment]
I guess your intention here is to use the singular hosted platform at Lyft for more sensitive pipelines. If so, then we should be able to support this soon.

**Comment by senthilnathan23** [comment]
> I guess your intention here is to use the singular hosted platform at Lyft for more sensitive pipelines. If so, then we should be able to support this soon.

Yes, that's right. Thank you!

**Comment by tekumara** [comment]
Hi all, I've taken a stab at a proposal for authz... Probably needs more work but thought I'd put it out there to start the discussion and get your input.
https://docs.google.com/document/d/1-dacHa0iaZl-Nq-nypfjbIqGq3m-Z2rp3T6AmLiburA/edit?usp=sharing

**Comment by kumare3** [comment]
Cc @kanterov @jeevb @EngHabu @wild-endeavor @pmahindrakar-oss @narape

**Comment by kumare3** [comment]
There is no standard for authZ available in open source, so we are closing this issue - until someone proposes a workable rfc
