### ISSUE TITLE
[BUG] Flytekit does not propagate the correct exit code for Spark failures

### ISSUE THREAD

**Issue by catalinii** [flyteorg/flyte#648]
**Describe the bug**
Running a spark job that fails in spark leads to an exit_code of 0. This prevents other tools from detecting the failure and mark it as success when it failed.

**Expected behavior**
Exit code of the script should NOT be 0

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Run a job that fails using Spark

**Screenshots**
` F \tat org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:973)""}"
 F \tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2239)""}"
 F \tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)""}"
 F \tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)""}"
 F \tat org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)""}"
 F \tat org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:775)""}"
 F \tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)""}"
 F \tat org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:195)""}"
 F \t... 33 more""}"
 F ""}"
 F ""}"
 F User error.""}"
 F ERROR:root:!!! End Error Captured by Flyte !!!""}"
 F INFO:root:Entering timed context: Writing (/tmp/engine_dir_1tg807_s -> s3://<REDACTED>)""}"
 F INFO:root:Output of command '['aws', 's3', 'cp', '--recursive', '--acl', 'bucket-owner-full-control', '/tmp/engine_dir_1tg807_s', 's3://<REDACTED>']':""}"
 F b'Completed 5.8 KiB/5.8 KiB (74.6 KiB/s) with 1 file(s) remaining\\rupload: ../tmp/engine_dir_1tg807_s/error.pb to s3://<REDACTED>\
'""}"
 F ""}"
 F INFO:root:Exiting timed context: Writing (/tmp/engine_dir_1tg807_s -> s3://<REDACTED>) [Wall Time: 0.654923473000963s, Process Time: 0.00427212499999996s]""}"
 F 20/12/17 04:56:18 INFO ShutdownHookManager: Shutdown hook called""}"
 F 20/12/17 04:56:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-d387401e-d88a-401f-b674-904279208462""}"
 F 20/12/17 04:56:18 INFO ShutdownHookManager: Deleting directory /var/data/spark-5b348a7e-e736-430b-9d5b-f7fa25b66ab4/spark-e73e48d0-8bc8-4819-86d6-1672eb66e70d""}"
 F 20/12/17 04:56:18 INFO ShutdownHookManager: Deleting directory /var/data/spark-5b348a7e-e736-430b-9d5b-f7fa25b66ab4/spark-e73e48d0-8bc8-4819-86d6-1672eb66e70d/pyspark-f71c9924-450d-4497-b4d6-ea4bad86d27e""}"
 F 20/12/17 04:56:18 INFO MetricsSystemImpl: Stopping s3a-file-system metrics system...""}"
 F 20/12/17 04:56:18 INFO MetricsSystemImpl: s3a-file-system metrics system stopped.""}"
 F 20/12/17 04:56:18 INFO MetricsSystemImpl: s3a-file-system metrics system shutdown complete.""}"
*** F 2020/12/17 04:56:18 Command /opt/spark/bin/spark-class completed with exit code 0""}"****`
**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [x ] Other

**Additional context**

**Comment by catalinii** [comment]
cc @akhurana001

**Comment by matthewphsmith** [comment]
Adding some context since @catalinii reached out to me offline.

She has a special scenario. Her team maintains a common image which embeds a few monitoring processes for the purposes of gathering information around Spark job failures. Essentially, they wrap the processes of spark-driver with some custom code and evaluate the exit code of the processes.

Flyte, by convention with Propeller, swallows failures where possible and returns a special error document. Propeller knows to read this/these document(s) when the container exit code is 0. However, this obviously creates problems for the above wrapping.

This offers a couple approaches/solutions which I will lay out and others can discuss merits:

1. Change the Wrapping Pattern - Is this wrapping necessary to observe the needed information from the process? Would it be possible to gather the same information via the Flyte API from a decoupled process?

2. Is swallowing the exit code correct of Flyte? Is the aforementioned pattern going to be common and Flyte is limiting the flexibility of teams that operate Flyte or want to specialize it for their company? Should Flyte provide different mechanisms for communicating "task failed but there is complete error information available at X path in s3" and use standard exit codes?

3. Specializing this behavior by extending flytekit: Write a simple engine extension which can be plugged in and provide specialized error handling that sends the necessary signal to the monitoring process. A basic how to:

a. this is the method which handles errors and writes the metainformation. This needs to be overridden or extended: https://github.com/lyft/flytekit/blob/d5684f2daada3eae78a8ea26998a37a59952e3c4/flytekit/engines/flyte/engine.py#L300

b. so if you create an engine module--which would really just be a near-copy of the engine.py above where you replace some code on error handling

c. the actual engine that is loaded can be modified by registering an identifier and module in the dict here: https://github.com/lyft/flytekit/blob/d5684f2daada3eae78a8ea26998a37a59952e3c4/flytekit/engines/loader.py#L7

d. then set the configuration in either the environment or the flytekit.conf file will cause your engine/error handling to be loaded https://github.com/lyft/flytekit/blob/d5684f2daada3eae78a8ea26998a37a59952e3c4/flytekit/engines/loader.py#L19

e. from there you can decide how to send the signal to the monitoring process. However, I believe there is a convention which necessitates that the container return exit code 0 to Flyte.

**Comment by kumare3** [comment]
This issue is no longer relevant in the new flytekit
