### ISSUE TITLE
[Core Feature] Flytekit local caching

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#761]
**Motivation: Why do you think this is important?**
Flytekit local caching

**Goal: What should the final outcome look like, ideally?**
Unclear, but probably a local file or some other state holding mechanism that flytekit can interact with between python processes that will respect output caching with the same semantics as data catalog.  Should also offer an easy way for users to reset this state.  Maybe print its contents.

**Describe alternatives you've considered**
None.

**Comment by katrogan** [comment]
Additional context:

There are currently [3 execution modes](https://github.com/flyteorg/flytekit/blob/7b5fd2ae2eed0feb062f95953cb0941743b3659e/flytekit/core/context_manager.py#L221,L236). `TASK_EXECUTION` is used for tasks in workflows run on hosted Flyte.

A potential first step to implementing this issue might be to take on `LOCAL_WORKFLOW_EXECUTION`, that is, when a workflow is run end to end on a user's machine. Starting here simplifies implementation since this already handles converting inputs and outputs from python native types to Flyte literals. The local caching story could make use of the existing [caching api](https://github.com/flyteorg/datacatalog/blob/master/protos/idl/service.proto), specifically: mirroring the `CreateDataset` and `GetDataset` interfaces.

Once `LOCAL_WORKFLOW_EXECUTION` is complete it might be easier to then move on to `LOCAL_TASK_EXECUTION` for running tasks locally.

**Comment by CodeMySky** [comment]
I supports this, I think it lowers the barrier on new adopters to test caching locally more easily.

**Comment by kumare3** [comment]
@CodeMySky this has been checked in, you can use the pre-release or try it out with next Flyte release
