### ISSUE TITLE
[BUG] PluginManager overrides resource Name and Namespace

### ISSUE THREAD

**Issue by regadas** [flyteorg/flyte#856]
**Describe the bug**
Users might need to have a different naming / namespace strategy for resources created by a given plugin.

If users set these properties they will get override by https://github.com/flyteorg/flytepropeller/blob/0d1eeabf9792cd16251545f2a463ee4329aa5706/pkg/controller/nodes/task/k8s/plugin_manager.go#L106

One reason users might feel the need to use a different name scheme is due to restrictions in length for k8s pod name and label values.

**Expected behavior**

Resource Name and Namespace should be respected.

**Comment by EngHabu** [comment]
For namespace, I think that's fair.. for name it is a little bit more complicated by retries.. if the plug-in generates the name based on the task template, it loses information about which retry is currently being attempted...
The name we force set here takes that into account.. and as far as I see, we don't expose this raw information in https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/core/exec_metadata.go#L24

I see a few ways out (depending on the motivation for why the change):
- Add RetryAttempt() in the above interface
- Instead of allowing plugins to set a name, we instead honor the GenerateName object property and if set, propeller can append retry number (and potentially other things) to the name

Cc @kumare3 too

**Comment by regadas** [comment]
There's one issue with the current approach where the name can be actually quite long and there might be plugins that take this name and use it as a prefix ... Imagine an operator that spawns several resources and each resource has a different suffix. This can easily exceed the limits for resource names (253) and if used in labels (63).

One question regarding this:

> if the plug-in generates the name based on the task template, it loses information about which retry is currently being attempted...

How important is it? is the name in that format is used for smth else other than being descriptive for the user?

**Comment by kumare3** [comment]
@regadas, the generated name if its too long, can be shortened by using a deterministic hash - Why can you not directly use the generated name? But, I think probably, there should be method on the TaskExecutionContext, that generates a name using your parameters.

This is the method that is used to generate a deterministic - unique name, of a fixed length
https://github.com/flyteorg/flytepropeller/blob/437a9f397f311deca8291e8e0cc086460eb04e6f/pkg/utils/encoder.go#L36

It is unique within some bounds!

**Comment by kumare3** [comment]
@regadas can we close this issue? I think the implementation satisfies your requirement right?

**Comment by regadas** [comment]
Hi @kumare3 yes! we can close this.
