### ISSUE TITLE
[BUG] Duration is not always calculated for task executions

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#885]
**Describe the bug**
Task execution durations are sometimes missing the started time as recorded by flyteadmin which makes computing the duration not possible since the started at and last updated at times are identical. However the UI should at least show the start time in this case, rather than rendering the start time and duration as '(unknown)'

**Expected behavior**
Task executions should always have defined start times.

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by kumare3** [comment]
UI rendering - 
![Screen Shot 2021-04-02 at 9 41 23 AM](https://user-images.githubusercontent.com/16888709/113435403-97bca700-9397-11eb-96ae-2464e7d32d7a.png)
Actual value returned by FlyteAdmin
![Screen Shot 2021-04-02 at 9 42 18 AM](https://user-images.githubusercontent.com/16888709/113435463-b7ec6600-9397-11eb-9248-391b98a0a8ea.png)

**Comment by csirius** [comment]
@katrogan 
The issue is that currently api response doesn't have `started_at` field.
From the backend code, I noticed it only returns this field if it's not `nil` value.

So two possibilities:
- `started_at` field is `nil` for the specified `task_execution` record.
- `started_at` is not processed at all.

FYI @jsonporter
