### ISSUE TITLE
[Flytekit] Issue with NamedTuple in Python 3.9 

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#914]
**Describe the bug**
When the task's output signature is given as `typing.NamedTuple`, it's throwing an error -- `flytekit.core.type_engine.RestrictedTypeError: Transformer for type <class 'tuple'> is restricted currently`. The same is working in Python 3.8

**Expected behavior**
There shouldn't be any error in the way. 

***To Reproduce***
1. Write a task with `typing.NamedTuple` as the output signature
2. Run the code locally/in a cluster

**Comment by fediazgon** [comment]
I will take this one.

The reason is that the `_field_type` attribute has been removed in Python 3.9 (see [typing.NamedTuple](https://docs.python.org/3/library/typing.html#typing.NamedTuple)). So [this statement in interface.py](https://github.com/flyteorg/flytekit/blob/master/flytekit/core/interface.py#L321) returns `False` in Python 3.9.

We have to find a new way of finding out if an object is a `NamedTuple`.
