### ISSUE TITLE
[Docs] Getting Started Navigation Menu

### ISSUE THREAD

**Issue by SandraGH5** [flyteorg/flyte#969]
https://docs.flyte.org/en/latest/getting_started.html
Getting Started navigates to Concepts -->Basics, even though menu shows the following section to be User Guide. Tutorials is also skipped.

Concepts then navigates to Community (skipping API Reference)

User Guide does not link to a following section - Tutorials is next on the menu.

Tutorials links to User Guide, but this is not shown on the menu.

Concepts --> Basics --> Glossary links to API Reference even though Core Concepts & Architecture are next on the menu.

**Comment by SandraGH5** [comment]
Update: 
Getting Started navigates to Concepts (skips User Guide and Tutorials)
API Reference: The [main page](https://docs.flyte.org/en/latest/reference/index.html) navigates to Community, but all of the embedded pages are disconnected from the navigation thread (FlyteCTL, FlyteIDL, FlyteKit, etc).
No navigation leads to User Guide.

**Comment by evalsocket** [comment]
@SandraGH5 Do we need new option in main menu for this page https://docs.flyte.org/en/latest/reference/index.html

**Comment by SandraGH5** [comment]
@evalsocket apologies if I wasn't clear. What I meant is that on the API page, the bottom navigation button under "Next" goes straight to Community, instead of going through Flytectl, Flytekit, Flyteidl, etc.

**Comment by evalsocket** [comment]
@SandraGH5 i think community is correct navigation because all these component has there on documentation. If we replace community with flytectl/flyteidl/flytekit then it will redirect us to a detail documentation of these component

cc: @samhita-alla

**Comment by samhita-alla** [comment]
> @SandraGH5 i think community is correct navigation because all these component has there on documentation. If we replace community with flytectl/flyteidl/flytekit then it will redirect us to a detail documentation of these component
> 
> cc: @samhita-alla

@evalsocket, Sandra says that the "Next page" links have to be in order. So, APIReference's next page has to be FlyteCTL, FlyteCTL's last page has to point to FlyteIDL, etc. But, @SandraGH5, I think that's not possible because FlyteCTL/FlyteIDL docs are under FlyteCTL and FlyteIDL repositories, respectively, whereas Getting started, API reference, community, etc. are under Flyte repository, and hence "Next page" is always pointing to a page that is in the same repository as that of the current page's repository. 

@cosmicBboy, you might have a better idea. What do you think?

**Comment by SandraGH5** [comment]
Thanks for clarifying @samhita-alla.
Is it possible to have the Next button redirect to a hyperlink (e.g. https://docs.flyte.org/projects/flytectl/en/stable/ for Flytectl) since it's not possible to point to a page in a different repo?

**Comment by samhita-alla** [comment]
I don't think so, @SandraGH5. I tried different techniques, but none is working. :/
We can disable "next page" if it doesn't look right.

**Comment by cosmicBboy** [comment]
I only solution I can think of is to update the furo theme templates: https://github.com/flyteorg/furo so that we can manually override the links that are auto-generated here: https://github.com/flyteorg/furo/blob/main/src/furo/theme/furo/page.html#L57-L82

We can adapt this approach: https://github.com/readthedocs/sphinx_rtd_theme/issues/921

**Comment by cosmicBboy** [comment]
@evalsocket let me know if you want me to take this on, I'm going to work on some updates to our furo fork anyway

**Comment by evalsocket** [comment]
@cosmicBboy sure

**Comment by cosmicBboy** [comment]
hey @SmritiSatyanV this is the ticket I referred to in standup. Let's chat about it next week!

**Comment by cosmicBboy** [comment]
Notes:
- here's the section in furo that determines the prev/next page links: https://github.com/flyteorg/furo/blob/main/src/furo/theme/furo/page.html#L58-L85
